---
dir:
  posts: "posts" 
  build: "build" 
  root: "." 
  fonts: "fonts"
filename: 
  index: "index.typ" 
  style: "style.css" 
  script: "script.js" 
  metadata: "post-list.json" 
font:
  active: "crimson-pro"