---
root:
  dir: "."
  index: "index.typ"
  script: "script.ts"
build:
  dir: "build"
fonts:
  dir: "fonts"
  default: "roboto"
  primary:
  secondary:
meta:
  dir: "meta"
  posts: "posts.json"
  fonts: "fonts.json"
posts:
  dir: "posts" 
styles:
  dir: "styles"
  style: "style.css"
assets:
  dir: "assets"