---
root:
  dir: "."
  index: "index.typ"
  script: "script.js"
build:
  dir: "build"
fonts:
  dir: "fonts"
  default: "crimson-pro"
  primary: "noto-serif"
  secondary: "roboto"
meta:
  dir: "meta"
  posts: "posts.json"
  fonts: "fonts.json"
posts:
  dir: "posts" 
styles:
  dir: "styles"
  style: "style.css"
assets:
  dir: "assets"